lesson17/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  #

  #get 'jokes/randon', 'jokes#random'

  resource :jokes, only: [] do
    get :random
  end

  scope :jwt, controller: 'jwt' do
    scope :jokes, controller: 'jwt/jokes' do
      get :random
    end

    scope :users, controller: 'jwt/users' do
      get :confirm, as: :confirm_user
    end
  end

  patch 'change_locale' => 'locales#change_locale'

  scope :currencies, controller: 'currencies' do
    get '/', action: :index
    get :convert
  end

  mount Sidekiq::Web => '/sidekiq'
end

lesson17/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

lesson17/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lesson17/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

lesson17/app/models/category.rb
class Category < ApplicationRecord
  has_many :jokes
end

lesson17/app/models/currency_rate.rb
class CurrencyRate < ApplicationRecord
end

lesson17/app/models/joke.rb
class Joke < ApplicationRecord
  belongs_to :category
end

lesson17/app/models/role.rb
class Role < ApplicationRecord
  USER = 'user'
  ADMIN = 'admin'
  AVAILABLE_ROLES = [USER, ADMIN].freeze

  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true
  validates :name,
            :inclusion => { :in => AVAILABLE_ROLES },
            allow_nil: false

  scopify
end

lesson17/app/models/user.rb
class User < ApplicationRecord
  rolify
  AVAILABLE_LOCALES = %w[en ru].freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :books

  after_create :assign_default_role

  def confirm!
    self.confirmed = true

    save!
  end

  private

  def assign_default_role
    self.add_role(Role::USER) if self.roles.blank?
  end
end

lesson17/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError do |_e|
    render json: { message: 'No access' }, status: 403
  end

  before_action :set_locale

  private

  def set_locale
    if user_signed_in?
      I18n.locale = current_user.locale
    else
      I18n.locale = I18n.default_locale
    end
    Rails.logger.info("CURRENT LOCALE #{I18n.locale}")
  end
end

lesson17/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[edit create update new destroy]
# GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize @book
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title)
    end
end

lesson17/app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  rescue_from Currencies::Requester::ServiceUnavailable do
    render json: { errors: 'Service unavailable' }, status: :service_unavailable
  end
  rescue_from Currencies::GetRate::BadParams do |e|
    render json: { errors: e.message }, status: :bad_request
  end

  caches_action :index

  def index
    render json: Currencies::AvailableCurrencies.call
  end

  def convert
    render json: Currencies::ConvertCurrency.call(from: params[:from], to: params[:to], amount: params[:amount])
  end
end

lesson17/app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def random
    sleep 20
    render json: Jokes::Random.call.to_json
  end
end

lesson17/app/controllers/jwt/jokes_controller.rb
module Jwt
  class JokesController < JwtController
    before_action :authenticate_user

    def random
      render json: Jokes::Random.call.to_json
    end
  end
end

lesson17/app/controllers/jwt/users_controller.rb
module Jwt
  class UsersController < JwtController
    def confirm
      Users::Confirmation::ConfirmMail.call(params['token'])

      redirect_to root_path
    end
  end
end

lesson17/app/controllers/jwt_controller.rb
class JwtController < ApplicationController
  class NotAuthenticated < StandardError; end

  JWT_SECRET = 'test_secret'

  rescue_from ActiveRecord::RecordNotFound do |_e|
    render status: 404, json: { message: 'User not found' }
  end

  rescue_from NotAuthenticated do |e|
    render status: 403, json: { message: e.message }
  end

  private

  def current_user
    return if decoded_token.blank?

    user_id = decoded_token['user_id']
    @user = User.find(user_id)
  end

  def logged_in?
    current_user.present?
  end

  def authenticate_user
    return if logged_in?

    raise NotAuthenticated, 'please log in'
  end

  def encode_token(payload)
    JWT.encode(payload, JWT_SECRET)
  end

  def auth_header
    request.headers['Authorization']
  end

  def decoded_token
    return if auth_header.blank?

    token = auth_header.split(' ').last
    begin
      JWT.decode(token, JWT_SECRET, true, algorithm: 'HS256').first
    rescue JWT::DecodeError
      nil
    end
  end
end

lesson17/app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  before_action :authenticate_user!

  def change_locale
    current_user.update(change_locale_permitted_params)

    render json: :ok
  end

  private

  def change_locale_permitted_params
    params.permit(:locale)
  end
end

lesson17/app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]

    def create
      super do |user|
        if user.persisted?
          Users::Confirmation::SendMailWorker.perform_async(user.id)
        end
      end
    end

    protected

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:locale, :avatar])
    end
  end
end

lesson17/app/helpers/application_helper.rb
module ApplicationHelper
end

lesson17/app/helpers/books_helper.rb
module BooksHelper
  def random_joke
    jokes_count = Joke.count
    Joke.find(rand(1..jokes_count))
  end
end

lesson17/app/helpers/test_helper.rb
module TestHelper
  def random_joke
    Joke.first
  end
end

lesson17/app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

</div>

lesson17/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lesson17/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

lesson17/app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>
  <%= I18n.t(:books) %>
</h1>

<div id="books">
  <% @books.each do |book| %>
    <div>
      <%= render book %>
      <p>
        <%= link_to "Show this book", book %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

lesson17/app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

lesson17/app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Back to books", books_path %> |
  <% if policy(@book).update? %>
    <%= link_to "Edit this book", edit_book_path(@book) %>
    <%= button_to "Destroy this book", @book, method: :delete %>
  <% end %>
</div>

lesson17/app/views/jokes/random.html.erb
<!DOCTYPE html>
<html>
<body>
<%= @joke %>
</body>
</html>

lesson17/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lesson17</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <% if user_signed_in? %>
        <%= current_user.email %>
        <% if current_user.avatar.attached? %>
          <%= image_tag(current_user.avatar.variant(resize_and_pad: [100, 100, gravity: 'north', background: '#000'])) %>
        <% end %>
        <%= link_to "Log out", destroy_user_session_path, data: { 'turbo-method': :delete } %>
      <% else %>
        <%= link_to "Log in", new_user_session_path %>
      <% end %>
    </div>

    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>


    <footer>
      <% if user_signed_in? %>
        <%= I18n.t('locale.change') %>
        <% User::AVAILABLE_LOCALES.each do |locale| %>
          <% next if locale == I18n.locale.to_s %>

          <%= button_to locale, change_locale_path, params: { locale: locale }, method: :patch %>
        <% end %>
      <% end %>
    </footer>
  </body>
</html>